# Generated by Django 2.1 on 2018-08-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(max_length=8192)),
                ('output_text', models.TextField(max_length=8192)),
            ],
        ),
    ]
